// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseTemplate: typeof import('./components/BaseTemplate.vue')['default']
    ButtonRepo: typeof import('./components/ButtonRepo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
  }
}

export { }
